
[terminal]
shell = "tmux"#"fish -c tmux attach || tmuxfish -c tmux attach || tmux"

  [env]
term = "xterm-256color"
winit_x11_scale_factor = "1"

[window]
dynamic_padding = true
# decorations = "full"
decorations = "none"
title = "terminal"
opacity = 0.85
decorations_theme_variant = "dark"
startup_mode = "maximized"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "alacritty"
general = "alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x0c0c0c"
# background = "0x2e3440"
foreground = "0xd8d8d8"

[colors.cursor]
cursor = "0xcccc00"

[colors.selection]
background = "0xcccccc"

[colors.normal]
black = "0x0c0c0c"
blue = "0x1258ff"
cyan = "0x3a96dd"
green = "0x13a10e"
magenta = "0x881798"
red = "0xC50F1F"
white = "0xCCCCCC"
yellow = "0xC19C00"

[colors.bright]
black = "0x868686"
blue = "0x3B78FF"
cyan = "0x61D6D6"
green = "0x16C60C"
magenta = "0xB4009E"
red = "0xE74856"
white = "0xF2F2F2"
yellow = "0xF9F1A5"


[font]
size = 12

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Underline"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
